### PR TITLE
Improved XML parsing.

### PR DESCRIPTION
**Pull request by vprzebinda**
Better handling when metar doesn't contain flight category ie when SPECI
is released. Now we look back up to 3 hours to get a flight category and
use the newest available metar with a flight category.

### CODE REVIEW

**Comment by WKHarmon** [comment]
Oh, hah ... someone who actually knows what they're doing looked at the code. Sweet. I ran out of Wemos modules and am waiting for some more, so I'll test and merge as soon as I get them.

**Review by WKHarmon — CHANGES_REQUESTED** [review]
You should probably remove your WiFi credentials, although the cat is mostly out of the bag now.

**Comment by vprzebinda** [comment]
lol. Free wifi at my house! thanks for the heads up.
-v

**Comment by WKHarmon** [comment]
@vprzebinda Hola! I know it's been a long time since you submitted this, but I haven't had a ton of time to work on it. Sorry for that. I've merged in most of your XML parsing changes and published a branch here: https://github.com/WKHarmon/led-sectional/tree/improved-parsing

This keeps most of the changes you made, but reimplements the light sensor, slightly changes the calculation for the the lightning LEDs, allows for a key, and reverts to most of the defaults that were in the original file (e.g. LED type, etc.)

I wasn't able to merge your more recent commits because it doesn't allow for an airport to appear on the list twice (some people have an inset that zooms in on a region that appears elsewhere on the map), and it makes it doesn't support a key (although that shouldn't be too hard to add). It also sends the key LEDs and NULL airports where there's a blank LED in the API request, but that doesn't really seem to hurt anything so it doesn't really matter.

I'm going to test this for a few weeks then merge it in, but if you wanted to look over it with my changes I'd welcome any feedback. When I have time I'll try to add the later commits in a way that doesn't break the other functionality, but I wanted to go ahead and push the earlier ones.

Thanks!

**Comment by WKHarmon** [comment]
I went ahead and merged the modified branch into master.

**Pull request closed without merging**
